#%RAML 1.0 NamedExample
   [{
                "categoryid":123,
                "category name":"laptop"
              },{
                "categoryid":1256,
                "category name":"laptop",
                
              }]
