#%RAML 1.0 NamedExampl
[{
	  "orderid" : 132,
	  "userid" : 123,
	  "addressid": 201,
	  "desicountid": 3,
	  "created" : "2019-05-12",
	  "modified": "2019-05-12",
	  "status": "shipped",
	  "amount": 550
        }, 
        {
	"orderid" : 132,
	"userid" : 123,
	"addressid": 201,
	"desicountid": 3,
	"created" : "2019-05-12",
	"modified": "2019-05-12",
	"status": "shipped",
	"amount": 550
}]