#%RAML 1.0 NamedExample
 [{
	"name": "Dell",
	"description": "Dell laptop",
	"price": 3456,
	"productId": 123,
	"categoryID": 12,
	"vedio_url": "dell.com"
},    
 {"name": "Dell",
	"description": "Dell laptop",
	"price": 3456,
	"productId": 123,
	"categoryID": 12,
	"vedio_url": "dell.com"
}]