#%RAML 1.0 Library
traits:
   404notfound: !include 404.raml
types:
  ProductDataType: !include product/ProductdataType.raml  
  useriddatatype: !include User/UserIddataType.raml
  userresponse: !include User/userresponsedataType.raml
  orderpost: !include Order/orderpostdataType.raml
  orderpayment: !include Order/orderpaymentdataType.raml
  orderpresponse: !include Order/order-post-responsdatatype.raml
securitySchemes:
  Ouathsecurity: !include securityScheme.raml
resourceTypes:
  collections: !include product/ProductresourceType.raml  
annotationTypes: 
   annotation: !include annotation.raml
