#%RAML 1.0 Overlay
extends: craft-online-shopping.raml
title: online-shopping
documentation:
  - title: overview
    content: this document defines about online shopping resource
    /product: 
      descrition: