#%RAML 1.0 NamedExample
catagories:
  [{
                "catagoryid": 11 ,
                  "name": "laptop"
                } ,
                {
                  "catagoryid": 12 ,
                  "name": "home electronics"
                } ,
                {
                  "catagoryid": 13 ,
                  "name": "mouse"
                } ,
                {
                  "catagoryid": 14 ,
                  "name": "mobile accesories"
                } ,
                {
                  "catagoryid": 15 ,
                  "name": "laptop shins"
                } ,
                {
                  "catagoryid": 16 ,
                  "name": "laptop covers"
                } , 
                {
                  "catagoryid": 17 ,
                  "name": "mens clothing"
                } ,
                {
                  "catagoryid": 18 ,
                  "name": "womens wardrob"
                } ,
                  {
                  "catagoryid": 19 ,
                  "name": "naming gigs"
                }  ,
                  {
                  "catagoryid": 20 ,
                  "name": "Study buddy"
                } 
               ]