#%RAML 1.0 NamedExample
Order:
  
   {
              "orderid": 55,
              "userid": 10,
              "uaddressid": 210,
              "discountid": 5,
              "created": "2019-05-15 12:39:30",
              "modified": "2019-05-15 15:39:30",
              "status": "Partially shipped",
              "amount": 9898
              }