#%RAML 1.0 NamedExample
Orders:
   [{
              "orderid": 51,
              "userid": 1,
              "uaddressid": 201,
              "discountid": 6,
              "created": "2019-05-15 12:39:30",
              "modified": "2019-05-15 15:39:30",
              "status": "shipped",
              "amount": 550
              } , {
              "orderid": 52,
              "userid": 2,
              "uaddressid": 202,
              "discountid": 8,
              "created": "2019-05-15 12:39:30",
              "modified": "null",
              "status": "shipped",
              "amount": 550
              },{
              "orderid": 53,
              "userid": 9,
              "uaddressid": 209,
              "discountid": 10,
              "created": "2019-05-15 12:39:30",
              "modified": "2019-05-15 15:39:30",
              "status": "awaiting payment",
              "amount": 952,},
              {
              "orderid": 54,
              "userid": 1,
              "uaddressid": 201,
              "discountid": 6,
              "created": "2019-05-15 12:39:30",
              "modified": "2019-05-15 15:39:30",
              "status": "shipped",
              "amount": 920
              }, {
              "orderid": 55,
              "userid": 10,
              "uaddressid": 210,
              "discountid": 5,
              "created": "2019-05-15 12:39:30",
              "modified": "2019-05-15 15:39:30",
              "status": "Partially shipped",
              "amount": 9898
              }

             ]     