#%RAML 1.0 NamedExample
Products:
  [
               {
                "catagory_id": 10,
                "description": "lenovu laptop",
                "name": "lenovu laptop",  
                "price": 1400,
                "product_id": 102,
                "video_url": "http://test.com/lenovo-laptop"           
                }   ,
                   {
                "catagory_id": 10,
                "description": "dell laptop",
                "name": "dell laptop",  
                "price": 1000,
                "product_id": 101,
                "video_url": "http://test.com/dell-laptop"           
                }     
                 ]  